// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package retrievebyxpathstring.actions;

import java.util.List;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.core.CoreRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class RetrieveByXPathString extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String Entity;
	private java.lang.String XPathString;

	public RetrieveByXPathString(IContext context, java.lang.String Entity, java.lang.String XPathString)
	{
		super(context);
		this.Entity = Entity;
		this.XPathString = XPathString;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.lang.String XPath = "//" + this.Entity.toString() + (this.XPathString == null ? "" : this.XPathString);
		List<IMendixObject> returnList = null;
		
		try { returnList = Core.retrieveXPathQuery(this.getContext(), XPath); }
		catch(CoreRuntimeException err) {
			Core.getLogger("RetrieveByXPathString").error("XPath '" + this.XPathString + "' seems to be invalid");
			throw err;
		}
		
		return returnList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveByXPathString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
